### ISSUE TITLE
Plink in a conda environment

### ISSUE THREAD

**Issue by HadrienG** [richelbilderbeek/plinkr#4]
**Is your feature request related to a problem? Please describe.**
I have plink installed in a conda environment and I'd like plinkr to use it instead of needing to install a new one.

**Describe the solution you'd like**
A `detect_plink()` or `use_plink(path = ...)` function that I can use to pass my own plink to plinkr

**Describe alternatives you've considered**
If the `install_plinks()` function would install plink in a conda environment I'd be equally happy

Best,
/Hadrien

**Comment by richelbilderbeek** [comment]
Not so fast, still need confirmation from the user :-)

**Comment by richelbilderbeek** [comment]
Hi @HadrienG,

This feature is ready to be tested.

```
remotes::install_github("richelbilderbeek/plinkr")
```

 * Custom install is described here: https://github.com/richelbilderbeek/plinkr/blob/master/doc/install.md#do-a-custom-plink-installation
 * Use a custom version of PLINK: https://github.com/richelbilderbeek/plinkr/blob/master/doc/faq.md#how-can-i-use-a-version-of-plink-i-have-installed-elsewhere

I would be interested to learn if calling PLINK v2 from plinkr would already work. I predict a probably-yes (for `run_plink`) and a maybe-yes for higher-level functions such as `assoc` and `assoc_qt`.

**Comment by HadrienG** [comment]
works well for plink 1.x 🎉 

```r
> plink_options <- create_custom_plink_options("~/.conda/envs/plink1/bin/")
> get_plink_version(plink_options)
[1] "v1.90"
> get_plink_exe_path(plink_options)
[1] "~/.conda/envs/plink1/bin//plink"
> plinkr::run_plink("--help", plink_options = plink_options)
[1] "PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/"
```

`run_plink` does not work for plink 2.x, I suspect because the executable is called `plink2` and not `plink`

**Comment by richelbilderbeek** [comment]
> run_plink does not work for plink 2.x, I suspect because the executable is called plink2 and not plink

Correct as of today! Note I have gotten it to work for PLINK 2.0 as well and it will be installed together with the other PLINKs as well. It is not on master yet, but v0.10 will also install PLINK2, as -apparently- some users want that :-)

Thanks for confirming this Issue, will happily close it!
