### ISSUE TITLE
plinkr installs wrong binary on mac

### ISSUE THREAD

**Issue by HadrienG** [richelbilderbeek/plinkr#5]
**Describe the bug**
`plinkr`installs the linux binary on macOS.

**To Reproduce**
Script to reproduce the behavior:

```r
run_plink("--help")
# [1] "sh: /Users/hadgo265/Library/Application Support/plinkr/plink_1_9/plink: cannot execute binary file"
# attr(,"status")
# [1] 126
# Warning message:
# In system2(command = normalizePath(plink_exe_path), args = args,  :
#  running command ''/Users/hadgo265/Library/Application Support/plinkr/plink_1_9/plink' --help --noweb 2>&1' had status 126
```

**Expected behavior**
I expected `plinkr` to download and install the mac binary instead of the linux one on MacOS
The path to the correct binary on macOS for plink 1.90 is `https://s3.amazonaws.com/plink1-assets/plink_mac_20210416.zip`

Best,
/Hadrien

**Comment by richelbilderbeek** [comment]
Hi @HadrienG, 

plinkr now downloads a Mac binary. This is confirmed to work on GitHub Actions, but we both know this is imperfect: nothing beats an install on a real Mac.

As I have no access to a Mac, I need a Mac user to confirm this works . Could you check? 

Running the code below should work or give a nice error reports:

```{r}
remotes::install_github("richelbilderbeek/plinkr")
plinkr::run_plink("--help")
plinkr::plinkr_report()
```

Thanks and cheers, Richel

**Comment by HadrienG** [comment]
I works now, thanks!
